name: "Publish every Git push to dev-fenhl to FlakeHub"
on:
  push:
    branches:
      - "dev-fenhl"
jobs:
  flakehub-publish:
    runs-on: "ubuntu-latest"
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "DeterminateSystems/determinate-nix-action@v3"
      - uses: "DeterminateSystems/flakehub-push@main"
        with:
          name: "fenhl/nixos-needsreboot"
          rolling: true
          visibility: "unlisted"
          include-output-paths: true
